#!/bin/sh


set -e

ROOT_DIR="`pwd`"
BUILD_DIR=build
SRC_DIR=emacs


rm -rf ${BUILD_DIR}
mkdir ${BUILD_DIR}

cd ${SRC_DIR}

if test -n "$1"; then
    commit="$1"
else
    commit="origin/master"
fi

git pull
git archive --format tar $commit | tar -C ../${BUILD_DIR} -xvf -

REV=`git log --no-color --pretty=format:%h ${commit}^..${commit} | head -n1`

cd ../${BUILD_DIR}

patch -p1  -i ../lion-fullscreen.patch 

STRINGS="
 nextstep/Cocoa/Emacs.base/Contents/Resources/English.lproj/InfoPlist.strings
 nextstep/Cocoa/Emacs.base/Contents/Info.plist"

TIMESTAMP="git log -n 1 --pretty='format:%at' $commit"
DAY=`date -u -r $TIMESTAMP +"%Y-%m-%d"`
ORIG=`grep ^AC_INIT configure.ac`
VNUM=`echo $ORIG | cut -d\  -f2-999 | sed s/\)$//`
VERS="$VNUM $DAY Git $REV"
DESCR="Emacs_Cocoa_${VNUM}_${DAY}_Git_${REV}"

#autogen/copy_autogen
./autogen.sh

# Use Homebrew libxml pkgconfig
export PKG_CONFIG_PATH=/usr/local/Library/Homebrew/pkgconfig

CFLAGS="${CFLAGS} -pipe -march=nocona"
export CC=gcc
export CFLAGS

./configure \
    --build=x86_64-apple-darwin \
    --without-dbus --with-ns

make bootstrap -j8 || make clean bootstrap && make install

for f in $STRINGS; do
    sed -e "s/$VNUM/$VERS/" -i '' $f
done


rm -rf _out
mkdir _out

rsync -aE nextstep/Emacs.app _out
rsync -aE ../emacs-dmg/* _out
rsync -aE ../emacs/src  _out/Emacs.app/Contents/Resources/


# Copy dylibs into the Emacs.app package
for f in `find  _out/Emacs.app/Contents/MacOS/ -type f`; do
    dylibbundler -of -cd  -b -x $f \
	-d _out/Emacs.app/Contents/Resources/lib \
	-p @executable_path/../Resources/lib/
done


Rez -o "_out/More.../Alternative Icon" _out/icon.r
rm _out/icon.r

# Set the finder info bit that says the file has a custom icon.
xattr -x -w com.apple.FinderInfo "00 00 00 00 00 00 00 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00" "_out/More.../Alternative Icon"

mv _out/dot-DS_Store _out/.DS_Store
SetFile -a Vc _out/background.*

rm -f ../tmp.dmg
hdiutil makehybrid -hfs -hfs-volume-name "$DESCR" -hfs-openfolder _out _out -o ../tmp.dmg
hdiutil convert -format UDZO ../tmp.dmg -o "../${DESCR}.dmg"

rm -rf ${BUILD_DIR}
rm -rf tmp.dmg
